---
title: "R 프로그래밍 기초 Part1"
author: 한상곤(sangkon@pusan.ac.kr)
date: "2023.06.13(화)" 
output:
  pdf_document: 
    extra_dependencies: kotex
    fig_height: 6
    fig_width: 10
    toc: yes
    fig_caption: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, fig.align = "center", message=F, warning=F, fig.height = 8, cache=T, dpi = 300, dev = "png")
```
# `R` 프로그래밍 관련 주요 Topic

## R 프로그래밍 언어 소개
- 1993년 뉴질랜드 오클랜드 대학의 통계학과 교수인 Ross Ihake, Robert Gentleman에 의해서 개발
- 통계 언어인 [`S`](https://en.wikipedia.org/wiki/S_(programming_language))의 계보를 잇고 있음
- R의 S+(S+PLUS)의 무료 버전으로 1993년 배포되어 현재는 GNU 프로젝트로 개발 및 개선

## R의 주요 특징
- 통계분석(Statistical Analysis)과 시각화(Visualization)을 위한 공개 소프트웨어로 활용되고 있음
  - 모든 데이터가 객체 형태로 관리
  - 고속 메모리 처리
  - 다양한 자료구조를 제공
  - 패키지 제공
  - 시각화 도구를 제공

## 작업 환경 구축하기
- R [공식 사이트](https://www.r-project.org)에서 무료로 다운로드 할 수 있음
  - 교재 `p.18`을 참고해서 진행
  - 패키지 설치를 위해서 `Rtools` 다운로드 후 설치
- [`RStudio`](https://posit.co/products/open-source/rstudio/) 다운로드 후 설치

## 패키지와 Session 보기

- `R` 패키지는 통계학 관련 교수와 학자 그리고 관련 개발자에 의해서 꾸준히 관리
  - 대부분의 패키지는 무료로 사용할 수 있음

## 패키지 설치와 삭제

1. 패키지는 `install.packages("패키지명")` 명령어를 사용해서 설치할 수 있다. `stringr` 패키지를 설치해보자.

```R
install.packages("stringr")
```

2. RStudio의 `Packages` 탭을 사용해도 설치가 가능하다.

3. 패키지를 사용하는 방법은 `library(패키지명)`, `require(패키지명)`으로 가능하다.

```{R}
library(stringr)
search() # 현재 사용하는 패키지 확인
```

4. 패키지 삭제는 `remove.packages("패키지명")`으로 가능하다.

## R Session

R Session이란 사용자가 R 프로그램을 기동한 이후 R 콘솔 시작과 종료 전까지의 기간에 수행된 정보를 의미

```{R}
sessionInfo()
```

## 작업 공간

- `setwd()`, 지정된 작업공간을 변경하기 위해서 사용
- `getwd()`, 지정된 작업공간을 확인하기 위해서 사용
```{R}
getwd()
```

## 데이터의 유형과 구조

`R`에서 제공하는 5가지 주요 자료구조는 다음과 같이 5가지 입니다.
- Vector(1차원)
- Matrix(2차원)
- Array(다차원)
- Data Frame(2차원 테이블 구조)
- List(중접 자료구조)

## Vector(벡터)(1차원)

- 일반적인 벡터는 `c()` 함수를 사용해서 작성할 수 있음

```{R}
c(1,2,3,4,5)
c(1:20)
seq(1, 10, 2)
rep(1:3, 3)
```

- 벡터 연산

```{R}
x <- c(1, 3, 5, 7)
y <- c(3, 5)
union(x, y) # 합집합
setdiff(x, y) # 차집합
intersect(x, y) # 교집합
```

- 벡터는 동일한 자료형으로 생성

```{R}
v1 <- c(33, -5, 20:23, 12, -2:3)
v2 <- c("홍길동", "이순신", "유관순")
v3 <- c(T, TRUE, FALSE, T, TRUE, F, T)
v4 <- c(33, 05, 20:23, 12, "4")
v1; v2; v3; v4
```

- `name`을 사용하면 컬럼명을 지정

```{R}
age <- c(30, 35, 40)
names(age) <- c("홍길동", "이순신", "강감찬") # 컬럼명을 지정할 수 있음
age
```

- 인덱스를 사용해서 벡터 참조 가능

```{R, error = T}
v1 <- c(13, -5, 20:23, 12, -2:3) # 생성
v1[1]
v1[c(2, 4)]
v1[c(3:5)]
v1[c(4, 5:8, 7)]
v1[-1]; v1[-c(2, 4)]; v1[-c(2:5)]; v1[-c(2, 5:10, 1)]
```
## Matrix(2차원)

- 행렬은 2차원 배열의 구조를 가지며, 벡터를 활용해서 행렬 객체를 생성할 수 있음

```{R}
m <- matrix(c(1:5))
m
```

- 벡터를 사용해서 열 우선으로 행렬 객체를 생성
```{R}
m <- matrix(c(1:10), nrow = 2)
m
```

- 행과 열의 수가 일치하지 않는 경우는 경우 부족한 데이터는 첫번째 데이터를 재사용

```{R}
m <- matrix(c(1:11), nrow = 2)
m
```

- 행 우선으로 데이터를 생성할 경우 가능하면 `byrow`를 사용해서 가독성을 확보

```{R}
m <- matrix(c(1:10), nrow = 2, byrow = T)
m
```

- 기존에 만들어준 벡터를 활용해서 행렬을 생성

```{R}
x1 <- c(m, 40, 50:52)
x2 <- c(30, 5, 6:8)
mr <- rbind(x1, x2)
mr
```

- 열을 기준으로 행렬을 생성할 수 있음

```{R}
mc <- cbind(x1, x2)
mc
```

- 행렬 생성 함수를 사용해서 행렬 객체를 생성할 수 있음

```{R}
m3 <- matrix(10:19, 2)
m4 <- matrix(10:20, 2)
m3  
m4
mode(m3); class(m3)  
```
  
- 인덱스(첨자)를 사용하여 행렬 객체에 접근할 수 있음
```{R}
m3[1, ]
m3[ , 5]
m3[2, 3]
m3[1, c(2:5)]
```

- 3행 3열의 행렬 객체 생성하는 방법인 행과 열의 크기를 정하는 것
```{R}
x <- matrix(c(1:9), nrow = 3, ncol = 3)
x
```

- 행렬의 크기와 형태를 확인하는 방법은 `length`와 `ncol`을 사용할 수 있음
```{R}
length(x)
ncol(x)
```

- `apply`를 사용해서 함수나 사용자 정의 함수를 적용할 수 있음
```{R}
apply(x, 1, max)
apply(x, 1, min)
apply(x, 2, mean)
```

- 사용자 정의 함수도 가능
```{R}
f <- function(x) {
  x * c(1, 2, 3)
}
result <- apply(x, 1, f)
result
```

```{R}
result <- apply(x, 2, f) # 1은 행, 2는 열
result
```

- 행렬 객체에 칼럼명을 지정할 수 있음
```{R}
colnames(x) <- c("one", "two", "three")
x
```

## Array(다차원)

- 배열을 생성하는 방법은 `array`를 활용하는 것
```{R}
vec <- c(1:12)
arr <- array(vec, c(3, 2, 2))
arr
```

- 배열 객체의 자료 조회하는 방법은 행렬과 유사
```{R}
arr[ , , 1]
arr[ , , 2]
mode(arr); class(arr)
```

## Data Frame(2차원 테이블 구조)

- 데이터 프레임은 열(!) 단위로 서로 다른 자료형을 포함할 수 있음

```{R}
no <- c(1, 2, 3)
name <- c("hong", "lee", "kim")
pay <- c(150, 250, 300)
vemp <- data.frame(No = no, Name = name, Pay = pay)
vemp
```

```{R}
m <- matrix(
  c(1, "hong", 150,
    2, "lee", 250,
    3, "kim", 300), 3, by = T)
memp <- data.frame(m)
memp
```

- 텍스트 파일을 활용해서 데이터프레임 객체를 생성
```{R}
getwd()
txtemp <- read.table('./data/emp.txt', header = 1, sep = "", fileEncoding = "euc-kr")
txtemp
```

- CSV 파일도 가능
```{R}
csvtemp <- read.csv('./data/emp.csv', header = T, fileEncoding = "euc-kr")
csvtemp
help(read.csv)
name <- c("사번", "이름", "급여")
read.csv('./data/emp.csv', header = F, col.names = name, fileEncoding = "euc-kr")
```

- 데이터 프레임을 생성하는 간단한 예제
```{R}
df <- data.frame(x = c(1:5), y = seq(2, 10, 2), z = c('a', 'b', 'c', 'd', 'e'))
df$x
str(df)
ncol(df)
nrow(df)
names(df)
df[c(2:3), 1]
summary(df)
```

- 데이터프레임 자료에 함수 적용하는 방법도 유사
```{R}
apply(df[ , c(1, 2)], 2, sum)
```

- 데이터프레임의 부분 객체 만들기는 방법은 `subset`을 활용
```{R}
x1 <- subset(df, x >= 3)
y1 <- subset(df, y <= 8)
xyand <- subset(df, x >= 2 & y <= 6)
xyor <- subset(df, x >= 2 | y <= 6)
```

- 데이터 프레임 병합은 `merge`를 사용
```{R}
height <- data.frame(id = c(1, 2), h = c(180, 175))
weight <- data.frame(id = c(1, 2), w = c(80, 75))
user <- merge(height, weight, by.x = "id", by.y = "id")
user
```

### List(중접 자료구조)

- 리스트를 생성하는 방법은 매우 간단
```{R}
list <- list("lee", "이순신", 95)
list
```

- 기존의 리스트를 벡터 구조로 변경하는 것도 가능
```{R}
unlist <- unlist(list)
unlist
```

- 1개 이상의 값을 갖는 리스트 객체 생성
```{R}
num <- list(c(1:5), c(6, 10))
num
```

- 리스트를 제대로 활용하는 방법은 key와 value 형식으로 리스트를 생성하는 것
```{R}
member <- list(name = c("홍길동", "유관순"), 
               age = c(35, 25),
               address = c("한양", "충남"), 
               gender = c("남자", "여자"),
               htype = c("아파트", "오피스텔"))
member$name
member$name[1]
member$name[2]
```

- 리스트의 key를 이용하여 value에 접근할 수 있다.
```{R}
member$age[1] <- 45
member$id <- "hong"
member$pwd <- "1234"
member$age <- NULL
length(member)
mode(member); class(member)
```

- 리스트 객체에 함수 적용하는 것도 유사
```{R}
a <- list(c(1:5))
b <- list(c(6:10))
lapply(c(a, b), max)
```

- 결과값을 벡터형식으로 확인하기 위해서는 별도의 함수를 사용
```{R}
sapply(c(a, b), max) 
```

- 다차원 리스트 객체 생성하는 방법은 내포된 리스트 형태
```{R}
multi_list <- list(c1 = list(1, 2, 3),
                   c2 = list(10, 20, 30), 
                   c3 = list(100, 200, 300))
multi_list$c1; multi_list$c2; multi_list$c3
```

- `do.call`을 사용해서 다차원 리스트를 열 단위로 바인딩할 수 있음
```{R}
do.call(cbind, multi_list)
class(do.call(cbind, multi_list))
```

## 문자열 처리
- 문자열 처리는 교재를 참고

## 데이터 불러오기 및 저장하기
- 교재를 참고