---
title: "Stock Prices of Popular Tech Companies"
author: Sangkon Han(sangkon@pusan.ac.kr)
date: "`r format(Sys.Date())`" 
output:
  pdf_document:
    extra_dependencies: ["kotex"]
    fig_height: 6
    fig_width: 10
    toc: yes
    toc_depth: 3
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes    
  word_document:
    fig_height: 6
    fig_width: 10
    toc: yes
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T,
                      fig.align="center",
                      message=F,
                      warning=F,
                      fig.height = 8,
                      cache=T,
                      dpi=300, 
                      dev="pdf")
library(tidyverse)
library(lubridate)
library(scales)
library(patchwork)
library(sysfonts)
library(showtext)
library(corrr)
library(rstatix)
library(prophet)
library(astsa)
library(forecast)
showtext_auto()
font_add_google("Roboto Slab", "Roboto")
theme_set(theme_minimal())
theme_update(plot.title = element_text(hjust = 0.5), text = element_text(family = "Roboto"))
```

# 데이터 읽어오기

```{r message=FALSE}
files <- list.files(path = "data/nasdaq_stock")
files
stocks <- read_csv(paste0("data/nasdaq_stock/", files), id = "name") %>% 
  mutate(name = gsub("data/nasdaq_stock/", "", name), name = gsub("\\.csv","",name)) %>% 
  rename_with(tolower)
stocks
```

## 결합

```{r message=FALSE}
big_tech_companies <- read_csv("data/nasdaq_stock_names.csv")
big_tech_companies
stocks <- 
  stocks %>% 
  inner_join(big_tech_companies, by = c("name" = "stock_symbol"))
stocks
```

# EDA

```{r}
end_labels <- 
  (stocks %>% 
     group_by(company) %>% 
     filter(date == max(date)) %>% 
     arrange(-open) %>% 
     select(open, company))[c(1:3,12:14),]

stocks %>% 
  ggplot(aes(date, open)) +
  geom_line(aes(color = company)) +
  scale_y_continuous(sec.axis = sec_axis(~., breaks = end_labels$open, 
                                         labels = end_labels$company)) +
  scale_x_date(expand = c(0,0)) +
  labs(x = "", y = "Open", color = "",
       title = "Opening Stock Prices of Major Tech Companies",
       subtitle = "Prices range from Jan 2010 to Jan 2023. The names shown are\nthe top and bottom 3 tech stocks at the most recent date.") +
  theme(legend.position = "none")
```

## Top and Bottom 3 Most Recent Open Values

```{r}
(stocks %>% 
  filter(company %in% end_labels$company[1:3]) %>% 
  ggplot(aes(date, open)) +
  geom_line(aes(color = company)) +
  facet_wrap(~company) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "Top 3", x = "")) /
(stocks %>% 
  filter(company %in% end_labels$company[-(1:3)]) %>% 
  ggplot(aes(date, open)) +
  geom_line(aes(color = company)) +
  facet_wrap(~company) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(title = "Bottom 3", x = ""))
```

## Peak Month

```{r}
stocks %>% 
  group_by(company) %>% 
  slice_max(open) %>% 
  filter(year(date) > 2020) %>% 
  mutate(month = month(date, label = TRUE),
         month = fct_relevel(month, "Jan", after = 12),
         month = fct_relevel(month, "Feb", after = 12)) %>% 
  ggplot(aes(month)) +
  geom_bar(color = "black", fill = "steelblue2") +
  geom_vline(xintercept = 5.5, linetype = "dashed") +
  geom_text(label = "2022", x = 5.8, y = 5, 
            color = "steelblue2", fontface = "bold") +
  geom_text(label = "2021", x = 5.2, y = 5,
            color = "steelblue2", fontface = "bold") +
  labs(title = "Peak Month for Tech Stocks", x = "", y = "Number of Stocks",
       subtitle = "Out of 13 tech stocks, 6 of them reached their peak in November 2021",
       caption = "IBM's peak was in March, 2013 and thus is not included.")
```

# Time Series

## Apple

```{r}
aapl <- stocks %>% 
  filter(name == "AAPL") %>% 
  select(ds = date, y = open)
```

```{r}
(aapl %>% 
  mutate(diff = c(NA, diff(y))) %>% 
  ggplot(aes(ds, diff)) + 
  geom_point(color = "steelblue4", alpha = 0.7) +
  labs(y = "Difference", x = "Date",
       title = "One Day Returns")
) /
(aapl %>% 
   mutate(diff = c(NA, diff(y))) %>% 
   ggplot(aes(diff)) +
   geom_histogram(bins = 50, fill = "steelblue4", color = "black")
)
```

### Prophet

```{r}
m_aapl <- prophet(aapl)
forecast <- predict(m_aapl, 
                    make_future_dataframe(m_aapl, periods = 140))
plot(m_aapl, forecast)
prophet_plot_components(m_aapl, forecast)
```

### ARIMA

```{r}
ts_aapl <- ts(aapl$y, start = c(2010, 4), frequency = 365)
aapl_fit <- window(ts_aapl, end = 2018)
```

```{r}
auto_arima_fit <- auto.arima(aapl_fit)
plot(forecast(auto_arima_fit, h = 365), ylim = c(0,200))
lines(window(ts_aapl, start = 2018), col = "red")
```

```{r}
plot(diff(log(aapl$y)),type = "l")
acf2(diff(log((aapl$y))))
```

```{r}
sarima.for(aapl_fit, 
           n.ahead = 365,
           2,1,3, 
           plot.all = TRUE)$plot
lines(window(ts_aapl, start = 2018), col = "red")
```

## IBM

### Prophet

```{r}
ibm <- stocks %>% 
  filter(name == "IBM") %>% 
  select(ds = date, y = open)
```

```{r}
m_ibm <- prophet(ibm)
forecast_ibm <- predict(m_ibm, 
                        make_future_dataframe(m_ibm, periods = 140))
plot(m_ibm, forecast_ibm)
prophet_plot_components(m_ibm, forecast_ibm)
```

### ARIMA

```{r}
plot(forecast(auto.arima(ibm$y), h = 365), ylim = c(0,250))
```

# Correlated Stocks

```{r}
(stock_corr <- stocks %>% 
  widyr::pairwise_cor(company, date, open) %>% 
  filter(item1 > item2) %>% 
  mutate(corrstr = ifelse(abs(correlation > 0.5), "Strong", "Weak"),
         type = ifelse(correlation > 0, "Positive", "Negative")) %>% 
  arrange(-abs(correlation)))
```

```{r}
stock_corr %>% 
  ggplot(aes(correlation)) +
  geom_histogram(aes(fill = type), 
                 alpha = 0.7, binwidth = 0.05) +
  xlim(c(-1,1)) +
  labs(title = "Distribution of Correlation Values",
       subtitle = "The majority of companies have a strong positive correlation",
       fill = "Positive Correlation") +
  theme(legend.position = c(0.2,0.8),
        legend.background = element_rect(fill = "white", color = "white"))
```

## IBM, The Outlier

```{r}
(stocks %>% 
  widyr::pairwise_cor(name, date, open) %>% 
  rename(var1 = item1, var2 = item2) %>% 
  cor_spread(value = "correlation") %>% 
  rename(term = rowname))[c(14,1:13),] %>% 
  network_plot() +
  labs(title = "Correlation of Tech Stocks") +
  theme(plot.title = element_text(hjust = 0.5),
        text = element_text(family = "Roboto"))

stocks %>% 
  ggplot(aes(date, open, color = name)) +
  geom_line() +
  gghighlight::gghighlight(name == "IBM", use_direct_label = FALSE) +
  labs(x = "", y = "", color = "",
       title = "IBM is an Outlier Among Tech Stocks")
```

## Positively Correlated

```{r}
stocks %>% 
  filter(company %in% 
           c(stock_corr[1:5,]$item1, stock_corr[1:5,]$item2)) %>% 
  ggplot(aes(date, open, color = company)) + 
  geom_line() +
  labs(x = "", y = "Open Price", color = "",
       title = "The 6 Most Correlated Stocks Have Nearly Identical Trends") +
  theme(legend.position = c(0.2,0.75),
        legend.background = element_rect(fill = "white",
                                         color = "white"))

stocks %>% 
  filter(company %in% c(stock_corr[1,1:2])) %>% 
  select(date, company, open) %>% 
  pivot_wider(names_from = company, values_from = open) %>% 
  ggplot(aes(`Adobe Inc.`, `Amazon.com, Inc.`)) +
  geom_point(alpha = 0.7, color = "steelblue2") +
  geom_smooth(method = "lm", se = FALSE, color = "black",
              linetype = "dashed") +
  labs(title = "Amazon and Adobe Trend")
```

## Negatively Correlated

```{r}
stock_corr %>% 
  filter(str_detect(item1, "Netflix") & str_detect(item2, "Machine"))

stocks %>% 
  filter(str_detect(company, "Netflix|Machine")) %>% 
  ggplot(aes(date, open, color = name)) + 
  geom_line() +
  labs(x = "", y = "Open Price", color = "",
       title = "IBM and Netflix Have Very Different Trends") +
  theme(legend.position = c(0.45,0.8))

stocks %>% 
  filter(str_detect(company, "Netflix|Machine")) %>% 
  select(date, name, open) %>% 
  pivot_wider(names_from = name, values_from = open) %>% 
  ggplot(aes(`IBM`, `NFLX`)) +
  geom_point(alpha = 0.7, color = "steelblue2") +
  geom_smooth(method = "lm", se = FALSE, color = "black",
              linetype = "dashed") +
  labs(title = "IBM and Netflix")
```

# Volatility

```{r}
stocks %>% 
  mutate(diff = close - open,
         col = ifelse(name == "IBM", "Yes", "No")) %>% 
  ggplot(aes(date, diff)) +
  geom_line(aes(color = col)) +
  facet_wrap(~name, scales = "free") +
  scale_color_manual(values = c("steelblue4", "red4")) +
  theme(legend.position = "none", plot.subtitle = element_text(hjust = 0.5)) +
  labs(title = 
         "IBM's Same Day Volatility is Unique with Respect to Other Tech Stocks",
       subtitle = "Difference = (Close - Open)")
```

```{r}
(stocks %>% 
  filter(name == "IBM") %>% 
  mutate(diff = close - open) %>% 
  ggplot(aes(date, diff)) +
  geom_line(color = "steelblue4") +
  labs(y = "Difference",
       title = "IBM's Open vs Close Difference")) /
(stocks %>% 
  filter(name == "AAPL") %>% 
  mutate(diff = close - open) %>% 
  ggplot(aes(date, diff)) +
  geom_line(color = "steelblue4") +
  labs(y = "Difference",
       title = "AAPL's Open vs Close Difference")) +
plot_annotation(title = "IBM's Volatility has Been Higher than Other Tech Stocks")
```

# Volume

```{r}
stocks %>% 
  mutate(volume = log(volume)) %>% 
  group_by(name) %>% 
  summarize(lm(close ~ volume, cur_data()) %>% tidy) %>% 
  filter(term == "volume", p.value < 0.01) %>% 
  arrange(-abs(estimate))

stocks %>% 
  ggplot(aes(volume, close, color = name)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", se = FALSE) +
  scale_x_log10() +
  scale_y_log10()

p.adjust(stocks %>% 
  mutate(volume = log(volume)) %>% 
  group_by(name) %>% 
  summarize(lm(close ~ volume, cur_data()) %>% tidy) %>% 
  filter(term == "volume") %>% 
  arrange(p.value) %>% 
  pull(p.value), method = "holm")
```