---
title: "R - Practice 01"
author: Sangkon Han(sangkon@pusan.ac.kr)
date: "`r format(Sys.Date())`" 
output:
  pdf_document:
    extra_dependencies: ["kotex"]
    fig_height: 6
    fig_width: 10
    toc: yes
    toc_depth: 3
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes    
  word_document:
    fig_height: 6
    fig_width: 10
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, message=F, warning=F, fig.height = 8, cache=T, dpi = 300, dev = "png")
library(tidyverse)
library(tidymodels)
library(ggplot2)
```

```{r}
df <- mpg
str(df)
nrow(df); ncol(df)
```

# dplyr & tidyr

## Manipulate variables(columns)

### select(), rename()

```{r}
df.car.info <- select(df, manufacturer, model, year)
```

```{r}
select(df, starts_with(match = "m"))
select(df, contains(match = "r"))
select(df, ends_with(match = "y"))
```

```{r}
select(df, 1:3)
select(df, c(2,5,7))
select(df, 9:11) 
select(df, (ncol(df)-2):ncol(df))
```

```{r}
df1 <- rename(df, mnfc = manufacturer, mod = model)
df1 <- select(df, mnfc = manufacturer, mod = model, everything())
```

### mutate() / transmute()

```{r}
df <- mutate(df, `avg miles per gallon` = (cty + hwy) / 2)
df <- mutate(df,
             car = paste(manufacturer, model, sep = " "),
             `cyl / trans` = paste(cyl, " cylinders", " / ", trans, " transmission", sep = ""))

```

```{r}
df1 <- transmute(df,
                 `avg miles per gallon` = (cty + hwy) / 2)
df1

df2 <- mutate(df,
             car = paste(manufacturer, model, sep = " "),
             `cyl / trans` = paste(cyl, " cylinders", " / ", trans, " transmission", sep = ""))
df2

df2 <- transmute(df,
             car = paste(manufacturer, model, sep = " "),
             `cyl / trans` = paste(cyl, " cylinders", " / ", trans, " transmission", sep = ""))
df2
```

## Manipulate variables(row)

### filter(), slice()

```{r}
filter(df, manufacturer == "audi") 
```

```{r}
filter(df, manufacturer == "audi" & year == 1999) 
```

```{r}
df1 <- filter(df, manufacturer == "audi" | manufacturer == "dodge")
df2 <- filter(df, manufacturer %in% c("audi", "dodge")) 
```

```{r}
filter(df, hwy >= 30)
```
```{r}
filter(df, year != 1999)
```
```{r}
slice(df, 1:5)
```

```{r}
slice(df, 20:30)
```
```{r}
slice(df, (nrow(df)-9):nrow(df))
```


### arrange

```{r}
# Sort rows by year (ascending order)
arrange(df, year)
```

```{r}
# Sort rows by year (descending order)
arrange(df, desc(year))
```

```{r}
# Sort rows by year (ascending order), cyl and displ
df.sort <- arrange(df, year, cyl, displ)
df.sort
```


### distinct
```{r}
df.example <- data.frame(id = 1:3, name = c("John", "Max", "Julia"))
df.example <- bind_rows(df.example, slice(df.example, 2)) # create duplicate of 2nd row
df.example <- arrange(df.example, id)
df.example
```


```{r}
# show table without duplicates
distinct(df.example)
```

```{r}
#  Back to mpg example - lets create a table with duplicates
df.dupl <- select(df, manufacturer, model)
df.dupl
```
```{r}
#   Keep only unique rows without duplicates
df.nodupl <- distinct(df.dupl)
df.nodupl
```
### Sample rows

```{r}
# sample_n() - Filter n randomly selected rows 
set.seed(42)
```

```{r}
# 10 randomly selected rows without replacement
sample_n(df, size = 10, replace = F)
```

```{r}
# 10 randomly selected rows with replacement
sample_n(df, size = 10, replace = T)
```

```{r}
# sample_frac() - Filter a fraction of randomly selected rows 
# 10% of table rows randomly selected
sample_frac(df, size = 0.1, replace = F)
```

### summarise
```{r}
# Calculate average hwy
summarise(df, `mean hwy` = mean(hwy))
```

```{r}
# Count table rows, and count distinct car models
summarise(df, rows = n(), `nr models` = n_distinct(model))
```

```{r}
# Calculate min / max hwy & cty
summarise(df, 
          `min hwy` = min(hwy),
          `min cty` = min(cty),
          `max hwy` = max(hwy),
          `max cty` = max(cty))
```

### group_by()

```{r}
# Group cars by manufacturer
group_by(df, manufacturer)
```

```{r}
# Combine summarise() & group_by() - summary statistics for grouped data
# Count number of cars for each manufacturer
summarise(group_by(df, manufacturer), cars = n())
```
```{r}
# Calculate mean / min / max hwy for each model
summarise(group_by(df, model),
          `mean hwy` = mean(hwy),
          `min hwy` = min(hwy),
          `max hwy` = max(hwy))
```

### count()
```{r}
# Count number of table rows
count(df)
```

```{r}
# Count number of cars per model
count(group_by(df, model))
```

## pipe operator `%>%`

```{r}
df %>% 
  filter(manufacturer == "audi") %>% 
  count()
```

```{r}
df %>% 
  filter(manufacturer %in% c("dodge", "chevrolet")) %>% 
  select(manufacturer, model, year, class)
```
```{r}
df %>% 
  group_by(manufacturer, model, class, trans) %>% 
  summarise(`mean hwy` = mean(hwy), cars = n()) %>% 
  ungroup() %>%
  filter(`mean hwy` > 30) %>% 
  arrange(desc(`mean hwy`))
```

## pivoting()

```{r}
table.long <- data.frame(id = 1:6,
                         type = c("a", "b", "a", "c", "c", "a"),
                         count = c(20, 50, 45, 15, 12, 5))
table.long
```

```{r}
table.wide <- pivot_wider(table.long, 
                          names_from = type, 
                          values_from = count)
table.wide
```

```{r}
table.long1 <- pivot_longer(table.wide, 
                            cols = c("a", "b", "c"), 
                            names_to = "type", 
                            values_to = "count", 
                            values_drop_na = T)
table.long1
```

```{r}
df.long <- df %>% 
  filter(manufacturer %in% c("jeep", "land rover", "hyundai")) %>% 
  select(model, trans, hwy) %>% 
  group_by(model, trans) %>% 
  summarise(`mean hwy` = mean(hwy)) %>% 
  ungroup()
df.long
```

```{r}
df.wide <- df.long %>% 
  pivot_wider(names_from = trans, 
              values_from = `mean hwy`)
df.wide
```

```{r}
df.long1 <- df.wide %>% 
  pivot_longer(-model,  # exclude column "model" and use all remaining columns!!!
               names_to = "trans", 
               values_to = "mean hwy", 
               values_drop_na = T)
df.long1
```


## separating and uniting

```{r}
dates <- seq.Date(from = as.Date("2021-01-01"), to = as.Date("2021-12-31"), by = "day") # generate dates
table <- data.frame(date = dates)
table %>% head(); table %>% tail()
```

### separate()
```{r}
table.sep <- table %>% 
  separate(data = ., 
           col = date, 
           into = c("year", "month", "dayofmonth"), 
           sep = "-") %>% 
  mutate(month = as.numeric(month),
         dayofmonth = as.numeric(dayofmonth)) %>% 
  arrange(year, month, dayofmonth)
table.sep
```

```{r}
table.sep_ <- table %>% 
  separate(data = ., 
           col = date, 
           into = c("year", "month", "dayofmonth"), 
           sep = "-") %>% 
  mutate_at(.tbl = .,                         # which table? - . stands for table in the pipe line!
            .vars = c("month", "dayofmonth"), # which variables are mutated?
            .funs = as.numeric) %>%           # which functions is applied?
  arrange(year, month, dayofmonth)
table.sep_
```

### unite()

```{r}
table.unite <- table.sep %>% 
  # add leading zeros
  mutate(month = str_pad(month, width = 2, side = "left", pad = "0"), # add leading zeros to month
         dayofmonth = str_pad(dayofmonth, width = 2, side = "left", pad = "0")) %>% # add leading zeros to dayofmonth
  unite(data = ., 
        col = "date", 
        year, month, dayofmonth, 
        sep = "-") %>% 
  arrange(date)
table.unite
```

```{r}
table.unite_ <- table.sep %>% 
  # add leading zeros
  mutate_at(.tbl = .,                              # which table? - . stands for table in the pipe line!
            .vars = c("month", "dayofmonth"),      # which variables are mutated?
            .funs = str_pad, 2, "left", "0") %>%   # which functions is applied? - function parameters are written down
  unite(data = ., 
        col = "date", 
        year, month, dayofmonth, 
        sep = "-") %>% 
  arrange(date)
table.unite_
```













